# Utilisation de la bibliothèque Numpy

## Import et création de tableaux 1D, 2D, 3D

In [73]:
import numpy as np

# Tableau 1D
arr1 = np.array([1, 2, 3, 4, 5])
print("Tableau 1D :")
print(arr1)

# Tableau 2D
arr2 = np.array([[1,2,3],[4,5,6]])
print("\nTableau 2D :")
print(arr2)

# Tableau 3D
arr3 = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
print("\nTableau 3D :")
print(arr3)

# Type et dimension
print("\nType du tableau :", type(arr1))
print("Dimension :", arr1.ndim)
print("Forme :", arr1.shape)
print("Type des éléments :", arr1.dtype)

Tableau 1D :
[1 2 3 4 5]

Tableau 2D :
[[1 2 3]
 [4 5 6]]

Tableau 3D :
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Type du tableau : <class 'numpy.ndarray'>
Dimension : 1
Forme : (5,)
Type des éléments : int64


## Création avec arange, linspace, zeros, ones, eye, full

In [74]:
# arange : similaire à range mais retourne un ndarray
arr = np.arange(0, 10, 2)  # 0,2,4,6,8
print("arange :", arr)

# linspace : N valeurs également espacées entre deux bornes
arr_lin = np.linspace(0, 1, 5)  # 0,0.25,0.5,0.75,1
print("linspace :", arr_lin)

# zeros et ones
print("Zeros :\n", np.zeros((2,3)))
print("Ones :\n", np.ones((3,2)))

# Identity matrix
print("Identity matrix 3x3 :\n", np.eye(3))

# Full : tableau rempli d'une valeur
print("Full 2x4 de 7 :\n", np.full((2,4), 7))

arange : [0 2 4 6 8]
linspace : [0.   0.25 0.5  0.75 1.  ]
Zeros :
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones :
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Identity matrix 3x3 :
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Full 2x4 de 7 :
 [[7 7 7 7]
 [7 7 7 7]]


## Indexation simple 1D / 2D

In [75]:
arr1 = np.array([10, 20, 30, 40, 50])
print("Élément à l'index 2 :", arr1[2])  # 30
print("Dernier élément :", arr1[-1])    # 50

arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("\nÉlément ligne 1, colonne 2 :", arr2[1,2])  # 6
print("Ligne 0 :", arr2[0,:])
print("Colonne 1 :", arr2[:,1])

Élément à l'index 2 : 30
Dernier élément : 50

Élément ligne 1, colonne 2 : 6
Ligne 0 : [1 2 3]
Colonne 1 : [2 5 8]


## Slicing et masques booléens

In [76]:
arr = np.arange(10)
print("Tableau complet :", arr)

# Slicing simple
print("Éléments index 2 à 5 :", arr[2:6])
print("Éléments pairs :", arr[::2])  # pas de 2

# Masque booléen
mask = arr % 2 == 0
print("Masque :", mask)
print("Éléments pairs via masque :", arr[mask])

Tableau complet : [0 1 2 3 4 5 6 7 8 9]
Éléments index 2 à 5 : [2 3 4 5]
Éléments pairs : [0 2 4 6 8]
Masque : [ True False  True False  True False  True False  True False]
Éléments pairs via masque : [0 2 4 6 8]


## Indexation avancée avec listes / arrays

In [77]:
arr = np.array([10, 20, 30, 40, 50])

# Indexation avec liste d'indices
indices = [0,2,4]
print("Éléments aux indices 0,2,4 :", arr[indices])

# Indexation avec un array numpy
arr_indices = np.array([1,3])
print("Éléments aux indices 1 et 3 :", arr[arr_indices])

# Indexation 2D avancée
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
rows = np.array([0,2])
cols = np.array([1,2])
print("Éléments arr2[rows, cols] :", arr2[rows, cols])  # [2,9]

Éléments aux indices 0,2,4 : [10 30 50]
Éléments aux indices 1 et 3 : [20 40]
Éléments arr2[rows, cols] : [2 9]


## Opérations élément par élément

In [78]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([10,20,30,40])

# Addition, soustraction, multiplication, division
print("Addition :", arr1 + arr2)
print("Soustraction :", arr2 - arr1)
print("Multiplication :", arr1 * arr2)
print("Division :", arr2 / arr1)

# Puissance et racine
print("Puissance :", arr1 ** 2)
print("Racine carrée :", np.sqrt(arr2))

Addition : [11 22 33 44]
Soustraction : [ 9 18 27 36]
Multiplication : [ 10  40  90 160]
Division : [10. 10. 10. 10.]
Puissance : [ 1  4  9 16]
Racine carrée : [3.16227766 4.47213595 5.47722558 6.32455532]


## Fonctions universelles (ufunc)

In [79]:
arr = np.array([0, np.pi/2, np.pi])

print("sin :", np.sin(arr))
print("cos :", np.cos(arr))
print("exp :", np.exp([1,2,3]))
print("log :", np.log([1, np.e, np.e**2]))
print("round :", np.round([1.2, 2.5, 3.7]))

sin : [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos : [ 1.000000e+00  6.123234e-17 -1.000000e+00]
exp : [ 2.71828183  7.3890561  20.08553692]
log : [0. 1. 2.]
round : [1. 2. 4.]


## Comparaisons et opérations logiques

In [80]:
arr = np.array([1,2,3,4,5])

# Comparaisons
print("arr > 3 :", arr > 3)
print("arr == 2 :", arr == 2)

# Opérations logiques
mask = (arr > 2) & (arr < 5)
print("2 < arr < 5 :", mask)

# Utiliser le masque pour filtrer
print("Éléments entre 2 et 5 :", arr[mask])

arr > 3 : [False False False  True  True]
arr == 2 : [False  True False False False]
2 < arr < 5 : [False False  True  True False]
Éléments entre 2 et 5 : [3 4]


## Moyenne, somme, min, max, std, var

In [81]:
arr = np.array([1, 2, 3, 4, 5])

print("Somme :", np.sum(arr))
print("Moyenne :", np.mean(arr))
print("Minimum :", np.min(arr))
print("Maximum :", np.max(arr))
print("Écart-type :", np.std(arr))
print("Variance :", np.var(arr))

Somme : 15
Moyenne : 3.0
Minimum : 1
Maximum : 5
Écart-type : 1.4142135623730951
Variance : 2.0


## Agrégations par axe (axis)

In [82]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

# Somme totale
print("Somme totale :", np.sum(arr2))

# Somme par colonne (axis=0)
print("Somme par colonne :", np.sum(arr2, axis=0))

# Somme par ligne (axis=1)
print("Somme par ligne :", np.sum(arr2, axis=1))

# Moyenne par ligne
print("Moyenne par ligne :", np.mean(arr2, axis=1))

Somme totale : 45
Somme par colonne : [12 15 18]
Somme par ligne : [ 6 15 24]
Moyenne par ligne : [2. 5. 8.]


## Cumulatives (cumsum, cumprod)

In [83]:
arr = np.array([1,2,3,4])

print("Somme cumulée :", np.cumsum(arr))
print("Produit cumulé :", np.cumprod(arr))

arr2 = np.array([[1,2],[3,4]])
print("Somme cumulée par colonne :", np.cumsum(arr2, axis=0))
print("Somme cumulée par ligne :", np.cumsum(arr2, axis=1))

Somme cumulée : [ 1  3  6 10]
Produit cumulé : [ 1  2  6 24]
Somme cumulée par colonne : [[1 2]
 [4 6]]
Somme cumulée par ligne : [[1 3]
 [3 7]]


## Reshape, flatten, ravel, transpose

In [84]:
arr = np.arange(12)  # 0 à 11
print("Tableau original :", arr)

# Reshape en 3x4
arr_reshaped = arr.reshape((3,4))
print("\nReshape 3x4 :\n", arr_reshaped)

# Flatten : transforme en 1D
arr_flat = arr_reshaped.flatten()
print("\nFlatten :", arr_flat)

# Ravel : vue 1D (pas de copie)
arr_ravel = arr_reshaped.ravel()
print("\nRavel :", arr_ravel)

# Transpose
print("\nTranspose :\n", arr_reshaped.T)

Tableau original : [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshape 3x4 :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flatten : [ 0  1  2  3  4  5  6  7  8  9 10 11]

Ravel : [ 0  1  2  3  4  5  6  7  8  9 10 11]

Transpose :
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## Concatenation (hstack, vstack, stack)

In [85]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

# Concatenation verticale (ajouter des lignes)
vstacked = np.vstack((a,b))
print("vstack :\n", vstacked)

# Concatenation horizontale (ajouter des colonnes)
hstacked = np.hstack((a,b))
print("\nhstack :\n", hstacked)

# Stack avec nouvel axe
stacked = np.stack((a,b), axis=0)
print("\nstack avec nouvel axe 0 :\n", stacked)

vstack :
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

hstack :
 [[1 2 5 6]
 [3 4 7 8]]

stack avec nouvel axe 0 :
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Split / array_split

In [86]:
arr = np.arange(10)
print("Tableau original :", arr)

# Split en 2 parties égales
parts = np.array_split(arr, 2)
print("\nSplit en 2 :", parts)

# Split en 3 parties (non égales possibles)
parts3 = np.array_split(arr, 3)
print("\nSplit en 3 :", parts3)

Tableau original : [0 1 2 3 4 5 6 7 8 9]

Split en 2 : [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

Split en 3 : [array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


## Produit matriciel (dot, @)

In [87]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

# Produit matriciel
prod1 = np.dot(A,B)
print("Produit avec np.dot :\n", prod1)

# Produit matriciel avec @
prod2 = A @ B
print("\nProduit avec @ :\n", prod2)

Produit avec np.dot :
 [[19 22]
 [43 50]]

Produit avec @ :
 [[19 22]
 [43 50]]


## Inverse, déterminant, valeurs propres

In [88]:
A = np.array([[2,1],[1,2]])

# Inverse
A_inv = np.linalg.inv(A)
print("Inverse de A :\n", A_inv)

# Determinant
det_A = np.linalg.det(A)
print("\nDeterminant de A :", det_A)

# Valeurs propres et vecteurs propres
eigvals, eigvecs = np.linalg.eig(A)
print("\nValeurs propres :", eigvals)
print("Vecteurs propres :\n", eigvecs)

Inverse de A :
 [[ 0.66666667 -0.33333333]
 [-0.33333333  0.66666667]]

Determinant de A : 2.9999999999999996

Valeurs propres : [3. 1.]
Vecteurs propres :
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


## Normes et traces

In [89]:
A = np.array([[1,2],[3,4]])

# Trace
print("Trace de A :", np.trace(A))

# Normes
print("Norme L2 (frobenius) :", np.linalg.norm(A))
print("Norme L1 :", np.linalg.norm(A, ord=1))
print("Norme infinie :", np.linalg.norm(A, ord=np.inf))

Trace de A : 5
Norme L2 (frobenius) : 5.477225575051661
Norme L1 : 6.0
Norme infinie : 7.0


## Génération de nombres aléatoires

In [90]:
# Random float uniforme [0,1)
arr_rand = np.random.rand(5)
print("Random float [0,1) :", arr_rand)

# Random float normale (moy=0, std=1)
arr_randn = np.random.randn(5)
print("\nRandom normale :", arr_randn)

# Random integers
arr_int = np.random.randint(0, 10, size=5)
print("\nRandom integers [0,10) :", arr_int)

Random float [0,1) : [0.59865848 0.15601864 0.15599452 0.05808361 0.86617615]

Random normale : [ 1.57921282  0.76743473 -0.46947439  0.54256004 -0.46341769]

Random integers [0,10) : [9 5 8 0 9]


## Seed, permutations, échantillonnage

In [91]:
np.random.seed(42)  # Pour reproductibilité
arr = np.random.randint(0, 100, size=10)
print("Tableau initial :", arr)

# Permutation aléatoire
perm = np.random.permutation(arr)
print("Permutation :", perm)

# Échantillonnage aléatoire sans remise
sample = np.random.choice(arr, size=5, replace=False)
print("Échantillon :", sample)

Tableau initial : [51 92 14 71 60 20 82 86 74 74]
Permutation : [51 82 74 92 74 20 14 71 60 86]
Échantillon : [20 14 86 82 74]


## Simulation simple (marche aléatoire)

In [92]:
steps = np.random.choice([-1,1], size=10)  # 10 pas, -1 ou +1
position = np.cumsum(steps)  # positions cumulées
print("Pas :", steps)
print("Positions cumulées :", position)

Pas : [-1 -1 -1  1  1  1  1  1 -1  1]
Positions cumulées : [-1 -2 -3 -2 -1  0  1  2  1  2]


## Broadcasting et opérations entre tableaux de formes différentes

In [93]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([10,20,30])

# Addition avec broadcasting
C = A + B
print("A :\n", A)
print("B :\n", B)
print("A + B avec broadcasting :\n", C)

# Multiplication
D = A * np.array([[1],[2]])
print("\nA * [[1],[2]] avec broadcasting :\n", D)

A :
 [[1 2 3]
 [4 5 6]]
B :
 [10 20 30]
A + B avec broadcasting :
 [[11 22 33]
 [14 25 36]]

A * [[1],[2]] avec broadcasting :
 [[ 1  2  3]
 [ 8 10 12]]


## Vectorisation avec np.vectorize

In [94]:
def f(x):
    return x**2 + 2*x + 1

f_vec = np.vectorize(f)  # vectorisation
arr = np.array([1,2,3,4])
print("Fonction vectorisée :", f_vec(arr))

Fonction vectorisée : [ 4  9 16 25]


## Masking et fancy indexing complexe

In [95]:
arr = np.arange(10)
mask = (arr % 2 == 0) | (arr > 7)
print("Masque :", mask)
print("Éléments filtrés :", arr[mask])

# Fancy indexing 2D
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
rows = np.array([0,2])
cols = np.array([1,2])
print("Éléments arr2[rows,cols] :", arr2[rows, cols])

Masque : [ True False  True False  True False  True False  True  True]
Éléments filtrés : [0 2 4 6 8 9]
Éléments arr2[rows,cols] : [2 9]


## Cheat Sheet NumPy

In [96]:
import numpy as np

# ==============================
# 1. Création de tableaux
# ==============================
np.array([1,2,3])                # tableau 1D
np.zeros((2,3))                  # tableau rempli de 0
np.ones((3,2))                    # tableau rempli de 1
np.full((2,2), 7)                # tableau rempli d'une valeur
np.eye(3)                         # matrice identité
np.arange(0,10,2)                 # similaire à range
np.linspace(0,1,5)                # valeurs espacées uniformément

# ==============================
# 2. Indexation et slicing
# ==============================
arr = np.arange(10)
arr[0], arr[-1]                   # indexation simple
arr[2:6], arr[::2]                # slicing
arr[arr>5]                         # masque booléen
arr[[0,2,4]]                       # fancy indexing

# ==============================
# 3. Opérations élémentaires
# ==============================
a = np.array([1,2,3])
b = np.array([10,20,30])
a + b, a - b, a*b, b/a, a**2
np.sqrt(b)
np.sin(a), np.cos(a)
(a > 1) & (b < 25)                 # comparaisons logiques

# ==============================
# 4. Statistiques
# ==============================
arr = np.array([[1,2,3],[4,5,6]])
np.sum(arr), np.mean(arr), np.min(arr), np.max(arr)
np.std(arr), np.var(arr)
np.sum(arr, axis=0), np.sum(arr, axis=1)
np.cumsum(arr), np.cumprod(arr)

# ==============================
# 5. Manipulation de forme
# ==============================
arr = np.array([[1,2,3],[4,5,6]])
print("reshape 3x2:\n", arr.reshape((3,2)))
print("reshape 6x1:\n", arr.reshape((6,1)))
arr.flatten(), arr.ravel()
arr.T                              # transpose
np.vstack([a,b]), np.hstack([a,b])
np.stack([a,b], axis=0)
np.array_split(arr, 3)

# ==============================
# 6. Algèbre linéaire
# ==============================
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
A @ B, np.dot(A,B)
np.linalg.inv(A)
np.linalg.det(A)
np.linalg.eig(A)
np.trace(A)
np.linalg.norm(A, ord=2), np.linalg.norm(A, ord=1), np.linalg.norm(A, ord=np.inf)

# ==============================
# 7. Random / simulations
# ==============================
np.random.rand(5), np.random.randn(5)
np.random.randint(0,10,5)
np.random.seed(42)
np.random.permutation(arr)
np.random.choice(arr.flatten(), size=5, replace=False)

# ==============================
# 8. Broadcasting et vectorisation
# ==============================
A = np.array([[1,2,3],[4,5,6]])  # 2x3
A + np.array([10,20,30])         # broadcasting correct

np.vectorize(lambda x: x**2 + 2*x +1)(arr)

# ==============================
# 9. Masking et fancy indexing avancé
# ==============================
mask = (arr % 2 == 0) | (arr > 7)
arr[mask]


reshape 3x2:
 [[1 2]
 [3 4]
 [5 6]]
reshape 6x1:
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


array([2, 4, 6])